## Modèle


In [1]:
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
import numpy as np
import pandas as pd


In [2]:
X = pd.read_pickle('datasets/X_all.pkl')

In [3]:
X.shape

(589, 132)

In [4]:
y = pd.read_pickle('datasets/y_all.pkl')

In [5]:
y.shape

(589,)

In [6]:
y = y.reshape((y.shape[0],1))

In [7]:
y.shape

(589, 1)

## Model split


In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [9]:
X_train.shape

(394, 132)

In [10]:
X_test.shape

(195, 132)

In [11]:
y_test.shape, y_train.shape


((195, 1), (394, 1))

## Model trained

In [32]:
model = Sequential([
    Dense(254, activation="relu", input_shape=(132,)),
    Dropout(0.3),
    Dense(128, activation="relu"),
    # Dropout(0.3),
    Dense(10, activation="softmax") ## 10 classes
])

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

c:\Users\mvana\anaconda3\envs\mediapipe-env\Lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [33]:
model.fit(
    X_train,
    y_train,
    epochs=500,
    batch_size=32
)

early_stop = EarlyStopping(
    monitor="val_loss",     # ce qu'on surveille
    patience=20,             # nb d'époques sans amélioration
    restore_best_weights=True
)

Epoch 1/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.1802 - loss: 2.2298   
Epoch 2/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3985 - loss: 1.9079 
Epoch 3/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4695 - loss: 1.6424 
Epoch 4/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6041 - loss: 1.3302 
Epoch 5/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6853 - loss: 1.0936 
Epoch 6/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7310 - loss: 0.9483 
Epoch 7/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7462 - loss: 0.8728 
Epoch 8/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7614 - loss: 0.7634 
Epoch 9/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7665 - loss: 0.7482 
Epoch 10/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8096 - loss: 0.6573 
Epoch 11/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8325 - loss: 0.5969 
Epoch 12/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/ste

In [34]:
pred = model.predict(X_test)
pose_id = np.argmax(pred, axis=1)



7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step 


In [35]:
pose_id

array([7, 3, 8, 4, 2, 1, 4, 2, 9, 5, 9, 0, 6, 2, 6, 2, 2, 9, 8, 2, 3, 2,
       0, 4, 2, 0, 0, 9, 3, 0, 5, 2, 9, 3, 1, 4, 3, 2, 9, 9, 3, 2, 2, 0,
       9, 8, 0, 9, 5, 3, 2, 9, 0, 7, 3, 6, 1, 1, 5, 4, 0, 8, 5, 0, 0, 2,
       5, 6, 9, 0, 6, 2, 9, 1, 5, 8, 0, 1, 2, 3, 2, 9, 9, 1, 5, 6, 1, 8,
       1, 3, 2, 9, 8, 3, 1, 3, 2, 1, 7, 0, 2, 5, 6, 3, 9, 6, 1, 2, 2, 8,
       5, 6, 1, 9, 1, 5, 5, 4, 1, 2, 1, 6, 3, 5, 2, 2, 1, 5, 0, 1, 3, 0,
       9, 9, 3, 1, 7, 1, 5, 9, 0, 0, 9, 4, 4, 5, 4, 3, 0, 6, 1, 1, 3, 8,
       0, 2, 4, 2, 3, 3, 8, 5, 5, 7, 7, 7, 0, 8, 0, 1, 5, 1, 4, 9, 7, 6,
       4, 5, 4, 5, 3, 7, 0, 7, 5, 3, 2, 2, 3, 2, 1, 6, 0, 2, 6])

In [36]:
pred


array([[4.4167959e-04, 6.9059331e-07, 1.2358284e-03, ..., 6.3060915e-01,
        3.6751074e-01, 2.3572846e-10],
       [1.2980062e-05, 1.4849588e-09, 8.2916467e-06, ..., 4.2477064e-04,
        1.5830955e-03, 2.0546695e-09],
       [4.2879714e-05, 1.8961742e-13, 9.6721693e-12, ..., 3.1147349e-05,
        9.9991989e-01, 2.7601004e-14],
       ...,
       [9.8040706e-01, 3.9128004e-08, 3.1980429e-09, ..., 1.8825959e-02,
        2.7097022e-04, 1.3343783e-10],
       [2.3744346e-19, 9.1180894e-19, 1.0000000e+00, ..., 1.4551937e-08,
        2.1480693e-09, 1.2817128e-27],
       [1.0230950e-12, 5.4510660e-17, 1.0652987e-15, ..., 5.8201469e-08,
        1.0952138e-12, 1.9641968e-22]], dtype=float32)

In [37]:
X_test[0:1].shape

(1, 132)

## Model Test 

In [38]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Évaluation Keras
loss, acc = model.evaluate(X_test, y_test, verbose=0)
print(f"Test loss: {loss:.4f}")
print(f"Test accuracy (keras): {acc:.4f}")


Test loss: 0.1148
Test accuracy (keras): 0.9692


In [39]:
# Accuracy "sklearn" + matrice de confusion (plus explicite)
y_proba = model.predict(X_test, verbose=0)
y_pred = np.argmax(y_proba, axis=1)
print(f"Test accuracy (sklearn): {accuracy_score(y_test, y_pred):.4f}")
print("\nConfusion matrix:\n", confusion_matrix(y_test, y_pred))

Test accuracy (sklearn): 0.9692

Confusion matrix:
 [[23  0  0  0  0  0  0  0  0  2]
 [ 0 25  0  0  0  1  0  0  0  0]
 [ 0  0 31  0  0  0  0  0  0  0]
 [ 0  0  0 23  0  0  0  0  0  0]
 [ 0  0  0  0 12  0  0  0  0  0]
 [ 0  0  0  0  0 21  0  0  0  0]
 [ 0  0  0  0  0  0 14  0  0  0]
 [ 1  0  0  0  0  0  0  9  0  0]
 [ 0  0  0  0  0  0  0  1 11  0]
 [ 0  0  0  0  1  0  0  0  0 20]]


In [40]:
# Si tu as un mapping label->nom
id2label = {0:"cobra", 1:"tree", 2:"downdog",3:"forwardfold",4:"chair",
            5:"warrior2",6:"warrior3",7:"plank",8:"child",9:"lotus"}  # adapte si besoin
print("\nClassification report:\n", classification_report(y_test, y_pred, target_names=[id2label[i] for i in sorted(id2label)]))


Classification report:
               precision    recall  f1-score   support

       cobra       0.96      0.92      0.94        25
        tree       1.00      0.96      0.98        26
     downdog       1.00      1.00      1.00        31
 forwardfold       1.00      1.00      1.00        23
       chair       0.92      1.00      0.96        12
    warrior2       0.95      1.00      0.98        21
    warrior3       1.00      1.00      1.00        14
       plank       0.90      0.90      0.90        10
       child       1.00      0.92      0.96        12
       lotus       0.91      0.95      0.93        21

    accuracy                           0.97       195
   macro avg       0.96      0.97      0.96       195
weighted avg       0.97      0.97      0.97       195



## Prediction du modèle avec une photo

In [41]:
import cv2
import os
import mediapipe as mp
from mediapipe import solutions
mp_drawing = mp.solutions.drawing_utils
mp_pose = mp.solutions.pose

In [42]:

data_root = r'C:\Users\mvana\Documents\Formation data scientist\20. ACV\Posture_yoga\data'
img_path = os.path.join(data_root, 'tree', 'PXL_20251217_103643021.MP.jpg')


In [43]:


def get_landmarks(image_rgb, pose_model): 
    '''
    Récupère les landmarks d'une image donnée en RGB via un modèle déjà chargé.
    Return: un numpy array (33,4) ou None si rien n'est trouvé.
    '''

    results = pose_model.process(image_rgb)
    
    if results.pose_landmarks:

        pose_np = np.array([[lm.x, lm.y, lm.z, lm.visibility] for lm in results.pose_landmarks.landmark])
        return pose_np

    return None

In [44]:
arbre = cv2.imread(img_path)

print("Image chargée:", arbre is not None)
image_rgb = cv2.cvtColor(arbre, cv2.COLOR_BGR2RGB)

Image chargée: True


In [45]:
with mp_pose.Pose(min_detection_confidence=0.5, min_tracking_confidence=0.5) as pose_model:

    landmarks = get_landmarks(image_rgb,pose_model)

In [46]:
landmarks_flatten = landmarks.flatten().reshape(1,-1)

In [47]:
landmarks_flatten.shape

(1, 132)

In [48]:
results = model.predict(landmarks_flatten)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step


In [49]:
results

array([[3.1189921e-16, 9.9540824e-01, 6.6789110e-14, 3.1634867e-22,
        5.5593308e-10, 4.5916000e-03, 7.0739347e-08, 1.4382297e-15,
        1.8759444e-19, 1.3497737e-14]], dtype=float32)

In [50]:
np.argmax(results)

np.int64(1)

## Save the model in pickle

In [51]:
model.save('yoga_model_10pose.keras')

In [54]:
import json
import os

# mapping (id -> label)
id2label = {
    0: "cobra",
    1: "tree",
    2: "downdog",
    3: "forwardfold",
    4: "chair",
    5: "warrior2",
    6: "warrior3",
    7: "plank",
    8: "child",
    9: "lotus",
}

# Crée la liste labels dans l'ordre des ids (TRÈS important)
labels = [id2label[i] for i in sorted(id2label.keys())]


config = {
    "model_path": "yoga_model_10pose.keras", 
    "num_classes": len(labels),
    "labels": labels,                       # ordre = indices de sortie du modèle
    "id2label": {str(k): v for k, v in id2label.items()},   # JSON => clés string
}

config_path = os.path.join("yoga_config.json")

with open(config_path, "w", encoding="utf-8") as f:
    json.dump(config, f, ensure_ascii=False, indent=2)

print("✅ Config écrite:", config_path)
print("labels:", labels)


✅ Config écrite: yoga_config.json
labels: ['cobra', 'tree', 'downdog', 'forwardfold', 'chair', 'warrior2', 'warrior3', 'plank', 'child', 'lotus']


In [55]:
config

{'model_path': 'yoga_model_10pose.keras',
 'num_classes': 10,
 'labels': ['cobra',
  'tree',
  'downdog',
  'forwardfold',
  'chair',
  'warrior2',
  'warrior3',
  'plank',
  'child',
  'lotus'],
 'id2label': {'0': 'cobra',
  '1': 'tree',
  '2': 'downdog',
  '3': 'forwardfold',
  '4': 'chair',
  '5': 'warrior2',
  '6': 'warrior3',
  '7': 'plank',
  '8': 'child',
  '9': 'lotus'}}