## Modèle


In [24]:
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
import numpy as np
import pandas as pd
import cv2


In [2]:
X = pd.read_pickle('datasets/X_all.pkl')

In [ ]:
X.shape

(992, 132)

In [4]:
y = pd.read_pickle('datasets/y_all.pkl')

In [5]:
y.shape

(992,)

In [6]:
y = y.reshape((y.shape[0],1))

In [7]:
y.shape

(992, 1)

## Model split


In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [9]:
X_train.shape

(664, 132)

In [10]:
X_test.shape

(328, 132)

In [11]:
y_test.shape, y_train.shape


((328, 1), (664, 1))

## Model trained

In [14]:
model = Sequential([
    Dense(254, activation="relu", input_shape=(132,)),
    Dropout(0.3),
    Dense(128, activation="relu"),
    #Dropout(0.3),
    Dense(11, activation="softmax")
])

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

In [49]:
model.fit(
    X_train,
    y_train,
    epochs=500,
    batch_size=32
)

early_stop = EarlyStopping(
    monitor="val_loss",     # ce qu'on surveille
    patience=20,             # nb d'époques sans amélioration
    restore_best_weights=True
)

Epoch 1/500
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0052 
Epoch 2/500
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9970 - loss: 0.0095 
Epoch 3/500
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9970 - loss: 0.0114 
Epoch 4/500
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9970 - loss: 0.0143     
Epoch 5/500
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9970 - loss: 0.0112 
Epoch 6/500
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9910 - loss: 0.0228 
Epoch 7/500
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9849 - loss: 0.0312 
Epoch 8/500
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9970 - loss: 0.0231 
Epoch 9/500
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9744 - loss: 0.0589 
Epoch 10/500
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9849 - loss: 0.0393 
Epoch 11/500
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9880 - loss: 0.0347 
Epoch 12/500
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/s

In [50]:
pred = model.predict(X_test)
pose_id = np.argmax(pred, axis=1)



11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 


In [51]:
pose_id

array([ 1,  2,  4,  2,  0,  4,  0,  0,  0,  4,  2,  3,  0,  0,  5,  6,  0,
       10,  0,  2,  1,  0,  6,  4,  4,  7, 10,  4,  3, 10,  7,  6,  5,  5,
        1,  5,  2, 10,  5,  5, 10,  0,  0,  6,  0,  1,  4,  5,  6,  2,  0,
        1,  9,  3,  3,  9,  5,  2,  1,  5,  3,  1,  9,  1,  2,  0,  9,  8,
        5,  0,  3,  0,  5,  2,  2,  1,  6,  7,  1,  9,  1,  2,  0, 10,  1,
        5,  6,  4,  2,  4,  1,  7,  2,  5, 10,  5,  0,  5,  1,  5, 10,  2,
        5,  5,  6,  1, 10,  2,  2,  9,  5,  0,  8,  4, 10,  1,  0,  8,  9,
        8,  0,  0,  0,  8,  0,  5,  6,  5,  7, 10,  1,  1,  7,  1,  2,  0,
        2,  9,  9, 10,  1,  1,  0, 10,  2,  9,  5,  5,  1,  1,  9,  1,  1,
        0,  1,  0,  9,  4,  2,  1,  7,  2,  9,  5,  7,  2,  3,  0,  2,  2,
        6,  7,  6,  5,  1,  1,  8,  7,  8,  0,  0,  9,  9,  3,  6,  1,  5,
        3,  3,  0,  0,  5,  6,  3,  5,  2,  7,  1,  6,  1,  1,  0,  6,  1,
        7, 10,  9,  4,  2, 10,  1,  5,  0,  0,  6,  1,  2,  8, 10,  2,  5,
        2,  0,  1,  0,  0

In [52]:
pred


array([[9.6860085e-13, 1.0000000e+00, 3.8123427e-18, ..., 7.3744591e-18,
        1.5476586e-18, 8.4521001e-11],
       [2.5809504e-16, 4.4450190e-21, 1.0000000e+00, ..., 6.9174746e-09,
        2.0906063e-10, 7.0103374e-34],
       [2.3348698e-02, 1.9791469e-02, 3.3044741e-17, ..., 3.0494270e-12,
        1.3490006e-06, 8.4993066e-03],
       ...,
       [3.8541985e-01, 1.1873587e-06, 6.1397678e-01, ..., 6.0171419e-04,
        8.0938012e-09, 7.5782765e-12],
       [2.0603075e-14, 3.6104336e-17, 1.0014326e-36, ..., 3.7828525e-31,
        3.0083556e-25, 1.0000000e+00],
       [1.8476502e-10, 9.9999762e-01, 3.2403462e-14, ..., 4.3002687e-14,
        9.7099569e-17, 2.2638003e-11]], dtype=float32)

In [53]:
X_test[0:1].shape

(1, 132)

## Model Test 

In [54]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Évaluation Keras
loss, acc = model.evaluate(X_test, y_test, verbose=0)
print(f"Test loss: {loss:.4f}")
print(f"Test accuracy (keras): {acc:.4f}")


Test loss: 0.8423
Test accuracy (keras): 0.9207


In [55]:
# Accuracy "sklearn" + matrice de confusion (plus explicite)
y_proba = model.predict(X_test, verbose=0)
y_pred = np.argmax(y_proba, axis=1)
print(f"Test accuracy (sklearn): {accuracy_score(y_test, y_pred):.4f}")
print("\nConfusion matrix:\n", confusion_matrix(y_test, y_pred))

Test accuracy (sklearn): 0.9207

Confusion matrix:
 [[49  0  0  0  0  0  0  0  0  0  0]
 [ 1 42  0  0  0  0  0  0  0  0  0]
 [ 1  0 50  0  0  0  0  0  0  0  0]
 [ 0  0  1 16  0  0  0  0  1  1  0]
 [ 2  4  0  0 14  2  0  0  0  0  0]
 [ 1  2  0  0  0 41  0  0  0  0  0]
 [ 0  0  0  0  0  0 22  0  0  0  0]
 [ 0  0  0  0  0  0  1 16  0  0  0]
 [ 3  1  1  0  0  1  0  1  8  1  0]
 [ 0  0  1  0  0  0  0  0  0 20  0]
 [ 0  0  0  0  0  0  0  0  0  0 24]]


In [56]:
# Si tu as un mapping label->nom
id2label = {0:"cobra", 1:"tree", 2:"downdog",3:"forwardfold",4:"chair",
            5:"warrior1",6:"warrior2",7:"warrior3",8:"plank",9:"child",10:"lotus"}  # adapte si besoin
print("\nClassification report:\n", classification_report(y_test, y_pred, target_names=[id2label[i] for i in sorted(id2label)]))


Classification report:
               precision    recall  f1-score   support

       cobra       0.86      1.00      0.92        49
        tree       0.86      0.98      0.91        43
     downdog       0.94      0.98      0.96        51
 forwardfold       1.00      0.84      0.91        19
       chair       1.00      0.64      0.78        22
    warrior1       0.93      0.93      0.93        44
    warrior2       0.96      1.00      0.98        22
    warrior3       0.94      0.94      0.94        17
       plank       0.89      0.50      0.64        16
       child       0.91      0.95      0.93        21
       lotus       1.00      1.00      1.00        24

    accuracy                           0.92       328
   macro avg       0.94      0.89      0.90       328
weighted avg       0.93      0.92      0.92       328



In [39]:
import cv2
import os
import mediapipe as mp
from mediapipe import solutions
mp_drawing = mp.solutions.drawing_utils
mp_pose = mp.solutions.pose

In [40]:

data_root = r'C:\Users\mvana\Documents\Formation data scientist\20. ACV\Posture_yoga\data'
img_path = os.path.join(data_root, 'tree', 'PXL_20251217_103643021.MP.jpg')


In [57]:


def get_landmarks(image_rgb, pose_model): 
    '''
    Récupère les landmarks d'une image donnée en RGB via un modèle déjà chargé.
    Return: un numpy array (33,4) ou None si rien n'est trouvé.
    '''

    results = pose_model.process(image_rgb)
    
    if results.pose_landmarks:

        pose_np = np.array([[lm.x, lm.y, lm.z, lm.visibility] for lm in results.pose_landmarks.landmark])
        return pose_np

    return None

In [58]:
arbre = cv2.imread(img_path)

print("Image chargée:", arbre is not None)
image_rgb = cv2.cvtColor(arbre, cv2.COLOR_BGR2RGB)

Image chargée: True


In [59]:
with mp_pose.Pose(min_detection_confidence=0.5, min_tracking_confidence=0.5) as pose_model:

    landmarks = get_landmarks(image_rgb,pose_model)

In [60]:
landmarks_flatten = landmarks.flatten().reshape(1,-1)

In [61]:
landmarks_flatten.shape

(1, 132)

In [62]:
results = model.predict(landmarks_flatten)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step


In [63]:
results

array([[1.1622178e-14, 1.0000000e+00, 1.5558637e-17, 1.0914766e-24,
        4.9400073e-14, 7.0423456e-10, 3.2726106e-09, 1.5313752e-16,
        1.1070876e-18, 2.4990616e-25, 1.3266350e-16]], dtype=float32)

In [64]:
np.argmax(results)

np.int64(1)

## Save the model in pickle

In [65]:
model.save('yoga_model_11pose.keras')